name: Main

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Easy Zip Files
      uses: vimtor/action-zip@v1
      with:
        files: src/
        dest: extension.zip
        recursive: true
        
    - name: Chrome Extension upload & publish
      uses: Passiverecords/chrome-extension-upload-action@1.4.1
      with:
        refresh-token: 'xxxxxxxxxxxxxxxxxxxxxx'
        client-id: 'xxxxxxxxxxxxx'
        client-secret: 'xxxxxxxxxxxx'
        file-name: './extension.zip'
        app-id: 'xzc12xzc21cx23'
        publish: true
